### ISSUE TITLE
unit updates

### ISSUE THREAD

**Issue by redurgam** [bcicen/xiny#6]
i see "mi" was added as a shorthand reference to mile in length_units.go, re: https://github.com/bcicen/go-units/issues/15
i tried re-compiling v0.3.3, but still don't have the updated shorthand mile reference in practice

i don't know how this works, but i see xiny/go.mod lists:
require (
...
github.com/bcicen/go-units v1.0.2
...
)
i don't see mention of the latest go-units v1.0.3

**Comment by bcicen** [comment]
thanks for pointing this out! updated now
